### ISSUE TITLE
Frameworks files not checked into repository

### ISSUE THREAD

**Issue by rcchen** [grant/snappo#8]
![image](https://cloud.githubusercontent.com/assets/1175041/5789378/f031cefa-9e35-11e4-8b78-3f2d3609c9c9.png)

**Comment by grant** [comment]
I don't think you can check them in. I'll add a little tutorial in the README to fix this.

**Comment by rcchen** [comment]
Might want to use [Cocoapods](http://cocoapods.org/) then (Ruby Bundler-like dependency manager system for external libraries)

**Comment by grant** [comment]
Would this work for adding FB's iOS SDK to the repo?

**Comment by rcchen** [comment]
Yeah, give me a couple min, I'll check it in.

**Comment by rcchen** [comment]
```
CocoaPods 0.36.0.beta.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Downloading dependencies
Installing Bolts (1.1.3)
Installing Facebook-iOS-SDK (3.22.0)
Generating Pods project
Integrating client project

[!] From now on use `app.xcworkspace`.
```

**Comment by grant** [comment]
Can you add a tutorial in the README? (`pull` first)

**Comment by rcchen** [comment]
:+1:

**Comment by grant** [comment]
i.e. which commands you use to install after cloning
